name: Reviewdog

on:
  pull_request:
    branches:
      - master

permissions: read-all

jobs:
  gofmt:
    name: Go Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - run: find . -not -path '*/\.git/*' -type f -name '*.go' -exec gofmt -s -w {} \+
      - uses: reviewdog/action-suggester@ecf27b2b88b6d83028e599a46517b4a1c18a72c6

  whitespace:
    name: Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - run: find . -not -path '*/\.git/*' -type f -not -name '*.go' -exec sed -i 's/[[:space:]]\{1,\}$//' {} \+
      - uses: reviewdog/action-suggester@ecf27b2b88b6d83028e599a46517b4a1c18a72c6
